"""Generate explicit template instantiations and print setup.py source entries.

Run from the repository root:
    python3 scripts/generate_instantiations.py csrc/ascend_kernels/prefill/sparse/instantiations

The script creates one .asc file per configuration and prints its relative path
for inclusion in setup.py. Unchanged files keep their modification timestamps.
"""

from pathlib import Path
import sys
from typing import List

INSTANTIATION_DIR = "csrc/ascend_kernels/prefill/sparse/instantiations"

# (format_name, mode, mode_name, extra_model_type)
CONFIGURATIONS = (
    ("v41", "Prefill", "prefill", "V41"),
    ("v41", "Decode", "decode", "V41"),
    ("v41fp4", "Decode", "decode", "V41_FP4"),
)

H_Q = 64
INDEX_BLOCK_SIZE = 640


def generate_instantiations(instantiation_dir: str) -> List[str]:
    if Path(instantiation_dir) != Path(INSTANTIATION_DIR):
        raise ValueError(f"Invalid instantiation_dir: {instantiation_dir}")
    repo_root = Path(__file__).resolve().parents[1]
    output_dir = repo_root / instantiation_dir
    output_dir.mkdir(parents=True, exist_ok=True)
    source_files = []
    for format_name, mode, mode_name, extra_model_type in CONFIGURATIONS:
        for have_attn_sink in (False, True):
            sink_name = "sink" if have_attn_sink else "nosink"
            path = output_dir / f"{format_name}_h{H_Q}_{mode_name}_{sink_name}.asc"
            content = (
                "// Generated by scripts/generate_instantiations.py.\n"
                '#include "../kernel.h"\n'
                '#include "../kernel_body.h"\n\n'
                "namespace ascend::prefill::sparse_fwd {\n\n"
                "template void run_sparse_fwd_kernel<Config{"
                f"SparseAttnFwdMode::{mode}, {H_Q}, {INDEX_BLOCK_SIZE}, {str(have_attn_sink).lower()}, "
                f"ModelType::V41, ModelType::{extra_model_type}"
                f"}}>(const ParamT<SparseAttnFwdMode::{mode}>& params);\n\n"
                "}\n"
            )
            if not path.exists() or path.read_text() != content:
                path.write_text(content)
            source_files.append(path.relative_to(repo_root).as_posix())
    return source_files


def main(instantiation_dir: str) -> None:
    for path in generate_instantiations(instantiation_dir):
        print(f'"{path}",')


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <instantiation_dir>")
        sys.exit(1)
    main(sys.argv[1])
